
project_id = "jfjcwxuzbgylgxbwlxmf"

[functions.process-audio]
regions = ["us-east-1", "eu-west-1", "ap-southeast-1"]

[functions.synthesize-speech]
regions = ["us-east-1", "eu-west-1", "ap-southeast-1"]
