// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jfjcwxuzbgylgxbwlxmf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImpmamN3eHV6Ymd5bGd4YndseG1mIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzU5Njg2NDQsImV4cCI6MjA1MTU0NDY0NH0.SACjlcxXR3uH35Fl3m-2BZfX5DOK1uFCJmzX1wwlWCg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);